<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A landlord after posting online his place for rent receives between 40 to 70
emails, with heavy attached document and no referals. With Olarent referals and notations system he is able to quickly
identify a renter and build a trusted relationship. Every month after the rental payment the landlord can evaluate his
tenant with a note, that will strenghten the system and the relationship.' => 'Un propriétaire aprés avoir posté une annonce en ligne pour son logement recoit entre 40 à 70 emails de locataires potentiels, avec de lourds pièces jointes comprenant leurs dossiers, sans aucun moyen d\'en verifier l\'authenticité. Olarent par son systeme de références et notations vous permet de créer une relation de confiance avec un locataire. Olarent vous donne la possiblité avec chaque paiement mensuel du loyer de donner une note à votre locataire, renforcant ainsi le systeme et la relation propriétaire - locataire.',
    'Absolutely. Olarent does not require your landlord to be signed up to use Olarent.
We send your landlord a wire payment on your behalf every month so you don’t have to.' => 'Absolument, Olarent ne requiert pas que votre propriétaire s\'inscrive, vous pouvez payer votre loyer depuis Olarent, nous enverrons votre loyer tous les mois à votre propriétaire.',
    'As long as you provide us the bank information (IBAN/RIB) of your landlord we
will wire him the money, even if he does not use Olarent or Internet at all.' => 'Du moment que vous pouvez nous fournir le RIB ou IBAN de votre propriétaire, nous serons en mesure de lui faire parvenir votre loyer, meme s\'ils n\'ont ni smartphone ni internet.',
    'Because it\'s more convenient than writing a check, finding a letter and a stamp
and not to forget to mail it, all of that in time every month.' => 'Parceque c\'est plus simple que de faire un cheque, trouver une enveloppe, un timbre, ne pas oublier de la poster, répeter l\'opération tous les mois.',
    'Finding a place to rent can be very hard.
Olarent enables you to show your renter profile to potential landlords, collect trusted referals from former landlords,
show your social media profile so potential landlords will be more likely to trust you and give you access to their properties.' => 'Trouver un logement peut parfois etre difficile, les dossiers et garanties requises peuvent parfois vous fermer des portes, la confiance peut etre difficile à établir. Olarent vous permet de mettre à disposition de propriétaires potentiels tout votre dossier en ligne, avec des références d\'anciens propriétaires et vos profils sur les réseaux sociaux pour créer les conditions de la confiance et vous ouvrir les portes de votre nouveau logement.',
    'How much does this cost ?' => 'Combien coute le service Olarent ?',
    'It\'s the only way to pay your rent online, mobile payment is seamless with a credit card or wire payment.' => 'C\'est le seul moyen de payer votre loyer en ligne, le paiement mobile est pratique et confortable avec une carte de crédit ou un virement.',
    'My landlord doesn’t use Olarent, or does not even have a smartphone, can I still Pay with Olarent?' => 'Mon propriétaire n\'utilise pas Olarent, ou n\'a ni smartphone ou internet, est ce que je peux quand meme utiliser Olarent?',
    'Why should I create a Tenant account ?' => 'Pourquoi créer un compte locataire ? ',
    'Why should I create a landlord account ?' => 'Pourquoi créer un compte propriétaire ?',
    'Why should I pay my rent with a credit card ?' => 'Pourquoi payer son loyer avec une carte de crédit ?',
    'Wire payment is 0,5% per transaction, while credit cards are 2% per transaction.' => 'Le virement bancaire represente 0,5% du montant de la transaction, la carte de crédit 2% par transaction.',
    'Your credit card has advantages a check does not have, your rent is taken off
your account immediately with a check, with your credit card you can benefit from your monthly debit for example or any airline miles that your card is associated with' => 'Votre carte de crédit a des avantages que votre carnet de cheque n\'a pas, vous pouvez bénéficier du débit différé si votre carte le permet ou du cumul des miles avec votre compagnie aérienne par exemple.',
];
