<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Dear Aruna,
<p>This is to inform that next payment to the property "12365" scheduled on 2016-03-25.</p>
<p>hello 123456 .</p>
Thank you.' => '',
    'Fund transfer failed' => '',
    'Fund transfer success' => '',
    'Missing bank details' => '',
    'Ola {tenantName},
<p></p>
<p>Congratulations ! You have successfully created your rental page for your landlord {ownerName}.
<br>The rental code is {propertyCode}
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => '',
    'Proof document validation failed' => '',
    'Rental creation confirmation' => '',
    'Tel:' => '',
    'Translate test' => '',
    '<br>Deposit charged:{amount}({currency})' => 'Dépôt de garantie {amount}({currency})',
    '<br>Initial rent charged:{cost}({currency})' => 'Montant du loyer {cost}({currency})',
    '<br>Initial rental charged:{cost}({currency})' => 'Montant du loyer {cost}({currency})',
    'All rental payment attempts have failed for "{code}"' => 'Echec des tentatives de paiement du loyer pour le logement "{code}"',
    'Card expiration on {date}' => 'Expiration de votre carte bancaire le {date}',
    'Copyright © {year} Olarent. All Rights Reserved.' => 'Droits d\'auteurs et de reproduction; {year} Olarent. Tous droits réservés.',
    'Email:' => 'Email:',
    'Failed rental payment for "{code}"' => 'Echec du paiement du loyer pour le logement "{code}"',
    'Ola {name},
<p></p>
<p>This message to inform that you have successfully created your Olarent account.
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que votre compte OlaRent a été créé avec succès.
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>This message to inform that your configured credit card is about to expire on {date}, please configure a new card.
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que votre carte de crédit configurée arrive à expiration le {date}, veuillez s\'il vous plait configurer une autre carte.
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>This message to inform you that the next payment to the rental "{code}" is scheduled on {nextChargingDate}.
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que le prochain paiement de votre loyer de pour le logement "{code}" est programmé pour le {nextChargingDate}.
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>This message to inform you that the rental "{code}" has been terminated by {terminatorName}.
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que {terminatorName} a mis fin à la location du logement "{code}".
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>This message to inform you that you have received all the pending payments of {amount}({currency}) for the rental "{code}"
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que vous avez reçu le paiement en attente de {amount}({currency}) pour le logement "{code}".
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>This message to inform you that you have successfully made the pending payment of {amount}({currency}) for the property "{code}"
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que vous avez effectué avec succès le paiement en attente de {amount}({currency}) pour le loyer du logement "{code}".
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>This message to inform you that you have terminated the rental "{code}".
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Nous vous informons que vous avez supprimé le logement "{code}".
<br>Merci.</p>',
    'Ola {name},
<p></p>
<p>Your password was successfully changed.
<br>Thank you.</p>' => 'Ola {name},
<p></p>
<p>Votre mot de passe a été réinitialisé avec succès.
<br>Merci.</p>',
    'Ola {ownerName},
<p></p>
<p>You have received a rental request from {tenantName}
<br>rental code is {propertyCode}
<br>Please respond as soon as you can to this inquiry.
<br>Thank you.</p>' => 'Ola {ownerName},
<p></p>
<p>Vous avez reçu une demande de location de {tenantName}
<br>Code logement {propertyCode}
<br>Nous vous invitons à y répondre.
<br>Merci.</p>',
    'Ola {ownerName},
<p>Tenant {tenantName} has successfully created a rental page for your property in Olarent.
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => 'Ola {ownerName},
<p>Votre locataire {tenantName} a créé la page de votre logement dans Olarent.
{msgKeymoney}
{msgInitRent}
<br>Merci.</p>',
    'Ola {ownerName},
<p>You have accepted the rental request of {tenantName} for the rental {propertyCode}.
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => 'Ola {ownerName},
<p>Nous vous informons que vous avez accepté une demande de location de {tenantName} pour le logement {propertyCode}.
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>',
    'Ola {tenantName},
<p></p>
<p>Congratulations ! Your rental request was accepted by {ownerName}
<br>The rental code is {propertyCode}
{msgKeymoney}
{msgInitRent}
<br>Thank you.</p>' => 'Ola {tenantName},
<p></p>
<p>Féliciations! Votre demande de location a été acceptée par {ownerName}
<br>Code logement {propertyCode}
{msgKeymoney}
{msgInitRent}
<br>Merci.</p>',
    'Ola {tenantName},
<p></p>
<p>Sorry your request for {propertyCode} was not accepted by {ownerName}, however he wishes you the best of luck in your search.
<br>We hope you will find another place you like on Olarent.
<br>Thank you.</p>' => 'Ola {tenantName},
<p></p>
<p>Désolé, votre demande de location pour {propertyCode} n\'a pas été acceptée par {ownerName}. Il vous souhaite cependant une bonne recherche.
<br>En espérant qu\'une autre location vous convienne sur Olarent.
<br>Merci.</p>',
    'Ola {tenantName},
<p></p>
<p>You have sent a rental request to {ownerName}
<br>rental code is {propertyCode}
<br>Thank you.</p>' => 'Ola {tenantName},
<p></p>
<p>Vous avez envoyé une demande de location à {ownerName}
<br>pour le logement {propertyCode}
<br>Merci.</p>',
    'Ola {toName}
<p></p>
<p>This message to inform you that the {amount} ({currency}) payment to the property "{code}" has failed. Please check your payment plan. We will try to complete the payment on {date} again.
<br>Thank you.</p>' => 'Ola {toName}
<p></p>
<p>Nous vous informons que le paiement du loyer de {amount} ({currency}) pour la  logement "{code}" a échoué. Veuillez vérifier votre moyen de paiement afin qu\'il puisse être complété avant le {date}..
<br>Merci.</p>',
    'Ola {toName}
<p></p>
<p>This message to inform you, your monthly rent have been charged {amount} ({currency}) for the property "{code}"
<br>Thank you.</p>' => 'Ola {toName}
<p></p>
<p>Nous vous confirmons que le paiement de {amount} ({currency}) pour votre logement "{code}" a bien été effectué."
<br>Merci.</p>',
    'Ola {toName},
<p></p>
<p>This message to inform you that all charging attempts made to the property "{code}" have failed. Please get in touch
with your landlord and check with your bank or update your Credit/Debit card information.
<br>Thank you.</p>' => 'Ola {toName},
<p></p>
<p>Nous vous informons que toutes les tentatives de paiements ont échoué pour la logement "{code}".
Veuillez prendre contact avec votre propriétaire et vous rapprocher de votre banque ou mettre à jour votre moyen de paiement dans Olarent.
<br>Merci.</p>',
    'Ola {toName},
<p></p>
<p>This message to inform you that all rental payment attempts have failed for "{code}".
Please get in touch with your tenant, we have advised him to update his payment method on Olarent.
<br>Thank you.</p>' => 'Ola {toName},
<p></p>
<p>Nous vous informons que toutes les tentatives de paiement pour la location "{code}" ont échoué.
Veuillez prendre contact avec votre locataire, nous lui avons conseillé de mettre à jour son moyen de paiement sur Olarent.
<br>Merci.</p>',
    'Ola {toName},
<p></p>
<p>This message to inform you that the {amount} ({currency}) payment for the property "{code}" has failed.
We will try again to complete the payment on {date}.
<br>Thank you.</p>' => 'Ola {toName},
<p></p>
<p>Nous vous informons que le paiement du loyer de {amount} ({currency}) pour la logement "{code}" a échoué.
Nous procèderons à une deuxieme tentative le {date}.
<br>Merci.</p>',
    'Ola {toName},
<p></p>
<p>This message to inform you, you have received the payment of {amount} ({currency}) for the property "{code}"
<br>Thank you.</p>' => 'Ola {toName},
<p></p>
<p>Nous vous confirmons que vous avez reçu le paiement du loyer de {amount} ({currency}) pour votre logement "{code}".
<br>Merci.</p>',
    'Ola {toName},
<p></p>
<p>You have received a review feedback from your former landlord {fromName}
<br>Thank you.</p>' => 'Ola {toName},
<p></p>
<p>Vous avez reçu une référence de votre ancien propriétaire {fromName}
<br>Merci.</p>',
    'Ola {toName},
<p></p>
<p>You have received a review request from your former Tenant {fromName}
<br>Thank you for your contribution !</p>' => 'Ola {toName},
<p></p>
<p>Vous avez reçu une demande de référence venant de votre ancien locataire {fromName} Cela vous prendra quelques secondes !
<br>Merci de votre contribution et à bientôt! Nous serions heureux de faciliter les échanges et règlements de
loyers avec vos futurs locataires.</p>',
    'Ola,
<p></p>
<p>Please, click on the following link to reset your password {link}
<br>Thank you.</p>' => 'Ola,
<p></p>
<p>Veuillez cliquer sur ce lien pour réinitialiser votre password {link}
<br>Merci.</p>',
    'Ola,
<p></p>
<p>{ownerName} has invited you to join Olarent to get to know you better and to make paying your rent easy and problem free.
<br>With Olarent you can pay your rent via Credit/Debit card and automate monthly payments.</p>
<p>Message from {ownerName}
<br><br>{message}<br>
<br>Go to our web app here:{appDownloadLink}
<br>Thank you.</p>' => 'Ola !,
<p></p>
<p>{ownerName}, propriétaire bailleur de votre appartement souhaite vous inviter à utiliser Olarent afin de faciliter
votre communication ainsi que les paiements de loyers. A vous de jouer!</p>
<p>Message de {ownerName}
<br>{message}
<br>Découvrez notre web app:{appDownloadLink}
<br>Merci.</p>',
    'Olarent Invitation from {ownerName}' => 'Invitation Olarent de la part de {ownerName}',
    'Olarent property management system.' => 'Olarent application de gestion des locations',
    'Pending payments have been made for "{code}"' => 'Le paiement en attente a été effectué pour "{code}"',
    'Pending payments have been received for "{code}"' => 'Le paiement en attente a été effectué pour "{code}"',
    'Rental  payment confirmation for "{code}"' => 'Confirmation du paiement du loyer pour "{code}"',
    'Rental payment attempt has failed for "{code}"' => 'La tentative de paiement du loyer a échoué pour "{code}"',
    'Rental payment confirmation' => 'Confirmation de paiement du loyer',
    'Rental request accepted from {ownerName}' => 'Demande de location acceptée par {ownerName}',
    'Rental request from {tenantName}' => 'Demande de location de {tenantName}',
    'Rental request to {ownerName}' => 'Votre demande de location à {ownerName}',
    'Rental termination confirmation for "{code}"' => 'Confirmation de la fin de location pour "{code}"',
    'Rental termination for "{code}"' => 'Fin de la location pour "{code}"',
    'Reset password' => 'Modifiez votre mot de passe',
    'Review feedback' => 'Vous avez reçu une référence',
    'Review request from {fromName}' => 'Demande de référence de {fromName}',
    'The Olarent Team' => 'L\'équipe Olarent',
    'The request was not accepted for the rental {propertyCode}' => 'La demande de location n\'a pas été accepté pour le logement {propertyCode}',
    'This month rental payment on {nextChargingDate}' => 'Le paiement de votre loyer est prévu pour le {nextChargingDate}',
    'Unsubscribe' => 'désinscription',
    'Welcome to Olarent {name}' => 'Bienvenue sur Olarent {name}',
    'You have accepted a rental request for "{code}"' => 'Vous avez accepté une demande de location pour "{code}"',
];
