<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You have accepted the request for rental {code} from tenant {tenantName}' => '',
    'You have successfully created the rental for the property of {ownerName}. Code is {code}' => '',
    'You have accepted the property {code} requested by tenant {tenantName}' => '@@Vous avez accepté la demande de {tenantName} pour le logement {code}@@',
    'Next payment date for the rental {code} will be on {date}' => 'Le prochain paiment de votre loyer pour le logement {code}  est prévu le {date}',
    'Payment {amount}({currency}) for the rental "{code}" has failed' => 'Votre règlement de loyer mensuel de {amount}({currency}) pour la location "{code}" n\'a pas abouti.',
    'This rental "{code}"  terminated' => 'Ce code logement "{code}" est supprimé',
    'You have received a request for your rental {code} from {tenantName}' => 'Vous avez reçu une demande pour votre logement {code} de {tenantName}',
    'You have received a review  from {senderName}' => 'Vous avez reçu un commentaire de {senderName}',
    'You have received a review request from {senderName}' => 'Vous avez reçu une demande de commentaire par {senderName}',
    'You have received a {amount}({currency}) payment to the rental "{code}"' => 'Vous avez reçu un paiement de {amount}({currency}) pour la location "{code}"',
    'Your credit card is about to expire on {date}. Please remember to add a new one.' => 'Votre carte bancaire va expirer sous peu, en date du {date}. Nous vous invitons à rensigner les informations de votre nouvelle carte dès que possible.',
    'Your monthly payment {amount}({currency}) for the rental "{code}" was successful' => 'Votre règlement de loyer mensuel de {amount}({currency}) pour la location "{code}" a bien été effectué.',
    'Your payment {amount}({currency}) for the rental "{code}" has failed' => 'Votre règlement de loyer mensuel de {amount}({currency}) pour la location "{code}" n\'a pas abouti.',
    'Your request for the rental {code} was accepted by owner {ownerName}' => 'Votre requète pour la location {code} a été acceptée par le propriétaire {ownerName} ',
    'Your request for the rental {code} was rejected by the owner {ownerName}' => 'Votre requète pour la location {code} a été déclinée par le propriétaire {ownerName} ',
];
